name: Use Actions Deploy Hexo To Github


on:
  push:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
      - name: Install hexo
        run: sudo npm install hexo-cli -g

      - name: Generate
        env:
          SOURCE_CODE: ${{ secrets.CODE }}
          THEME_WAREHOUSE: ${{ secrets.THEME }}
        run: |
          git clone -b master https://github.com/axpv-code/ndajknkdnclasmckascla gh
          cd gh
          npm install
          rm -rf .github
          rm -rf .gitignore
          git clone https://github.com/axpv-code/hexo-theme-diaspora themes/themes
          ${{ secrets.OTHER }}
          hexo generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./gh/public
          publish_branch: hexo
          personal_token: ${{ secrets.TOKEN }}
